const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger-output.json'
const endpointsFiles = ['./routers/index.js']


const doc = {
    info: {
        version: "1.0.0",
        title: "Calendar API",
        description: "Calendar API, provides users to manage their time, events and tasks to get a comfortable life. Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:5000",
    basePath: "/api",
    schemes: ['http', 'https'],
    consumes: ['application/json','text/plain'],
    produces: ['application/json','text/plain'],
    tags: [
        {
            "name": "Auth",
            "description": "Authentication Endpoints"
        }
    ],
    securityDefinitions: {
        Authorization: {
            type: "apiKey",
            in: "header", // can be "header", "query" or "cookie"
            name: "authorization", // name of the header, query parameter or cookie
            description:
                "Please enter a valid token to test the requests below...",
        },
    },
    definitions: {
        User: {
            name: "Jhon Doe",
            age: 29,
            parents: {
                father: "Simon Doe",
                mother: "Marie Doe"
            },
            diplomas: [
                {
                    school: "XYZ University",
                    year: 2020,
                    completed: true,
                    internship: {
                        hours: 290,
                        location: "XYZ Company"
                    }
                }
            ]
        },
        RegisterUser: {
            $name:"string",
            $email:"string",
            $password:"string"
        }
    }
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./server.js')
})